# Generated by Django 4.1.5 on 2023-01-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_contact_fullname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Data',
        ),
    ]
